### ISSUE TITLE
ASIS-asis-gpl-2017-src Compilations issues

### ISSUE THREAD

**Issue by swapniljarali** [simonjwright/ASIS#1]
I have pulled the ASIS-asis-gpl-2017-src for GNAT 17.1 and tried to compile the ASIS but i am geeting the compilation errors, please find them as below:
c:\gnatpro\17.1\bin\gcc.exe -c -x ada -gnatA -gnatf -gnatws -O2 -gnatec=C:\Users\sjarali\Downloads\ASIS-asis-gpl-2017-src\ASIS-asis-gpl-2017-src\obj\GNAT-TEMP-000002.TMP -gnatem=C:\Users\sjarali\Downloads\ASIS-asis-gpl-2017-src\ASIS-asis-gpl-2017-src\obj\GNAT-TEMP-000006.TMP C:\Users\sjarali\Downloads\ASIS-asis-gpl-2017-src\ASIS-asis-gpl-2017-src\asis\asis-text-set_get.adb
a4g-contt.ads:391:06: unmatched actual "Table_Name"
a4g-contt.ads:391:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:399:06: unmatched actual "Table_Name"
a4g-contt.ads:399:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:407:06: unmatched actual "Table_Name"
a4g-contt.ads:407:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:413:40: "Saved_Table" not declared in "A_Name_Chars"
a4g-contt.ads:415:38: "Saved_Table" not declared in "Unit_Table"
a4g-contt.ads:416:38: "Saved_Table" not declared in "Tree_Table"
a4g-contt.ads:527:06: unmatched actual "Table_Name"
a4g-contt.ads:527:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:272:06: unmatched actual "Table_Name"
a4g-a_elists.ads:272:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:285:06: unmatched actual "Table_Name"
a4g-a_elists.ads:285:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:288:27: "Saved_Table" not declared in "Elmts"
a4g-a_elists.ads:289:28: "Saved_Table" not declared in "Elists"
a4g-contt.ads:391:06: unmatched actual "Table_Name"
a4g-contt.ads:391:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:399:06: unmatched actual "Table_Name"
a4g-contt.ads:399:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:407:06: unmatched actual "Table_Name"
a4g-contt.ads:407:06: in instantiation of "Table" declared at g-table.ads:56
a4g-contt.ads:413:40: "Saved_Table" not declared in "A_Name_Chars"
a4g-contt.ads:415:38: "Saved_Table" not declared in "Unit_Table"
a4g-contt.ads:416:38: "Saved_Table" not declared in "Tree_Table"
a4g-contt.ads:527:06: unmatched actual "Table_Name"
a4g-contt.ads:527:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:272:06: unmatched actual "Table_Name"
a4g-a_elists.ads:272:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:285:06: unmatched actual "Table_Name"
a4g-a_elists.ads:285:06: in instantiation of "Table" declared at g-table.ads:56
a4g-a_elists.ads:288:27: "Saved_Table" not declared in "Elmts"
a4g-a_elists.ads:289:28: "Saved_Table" not declared in "Elists"

   compilation of asis-text-set_get.adb failed
   compilation of asis-text.adb failed

**Comment by simonjwright** [comment]
I see you’re using GNAT PRO 17.1; this repo is aimed at building ASIS for the FSF version of GNAT. The ASIS code is tightly coupled to the compiler, and needs a close version match to have a hope of succeeding.

GNAT PRO compilers are normally only accessible to AdaCore customers with support contracts. If you are such a customer, you need to get support from AdaCore (I seem to remember there’s an extra cost).

I don’t believe that the 17 in GNAT PRO 17.1 has anything to do with the 2017 in asis-gpl-2017-src! You might possibly have more luck with the tag asis-gpl-2018-20180523-src here.
